server.address=0.0.0.0
spring.config.import=optional:file:.env[.properties]

spring.application.name=${SPRING_APPLICATION_NAME:lms}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/lms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

telegram.client-id=${TELEGRAM_CLIENT_ID}

IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB