server.address=0.0.0.0

spring.application.name=${SPRING_APPLICATION_NAME:lms}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/lms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}

telegram.client-id=${TELEGRAM_CLIENT_ID:test}
imagekit.private-key=${IMAGEKIT_PRIVATE_KEY:test}

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
