# ---------- Build stage ----------
FROM ghcr.io/graalvm/native-image-community:23 AS build
WORKDIR /app
RUN microdnf install -y maven
COPY pom.xml .
RUN mvn -B dependency:go-offline -Pnative
COPY src ./src
RUN mvn -B clean package -Pnative -DskipTests

# ---------- Runtime stage ----------
FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
COPY --from=build /app/target/app .
ENV PORT=8080
ENTRYPOINT ["./app"]
